### ISSUE TITLE
Any BGEE / BG2EE support?

### ISSUE THREAD

**Issue by ahungry** [FredrikLindgren/aTweaks#12]
Just wondering if this is supported there - or if this module is superseded by the Tweaks Anthology or anything?

**Comment by CamDawg** [comment]
aTweaks works fully on the EEs AFAIK. Regardless, Tweaks Anthology is not a replacement for it.

**Comment by ahungry** [comment]
Thanks - I just went for it and gave it a go - it's been working flawlessly (and I now see they are distinct and Tweaks Anthology = cdtweaks, while aTweaks = atweaks in the install stuff)

**Comment by FredrikLindgren** [comment]
For information: parts of aTweaks are unavilable for BG:EE, because aTweaks rests heavily on the assumption that BG1-type games include BG2 resources, which BG:EE does not.
