### ISSUE TITLE
XP value for rift guardians

### ISSUE THREAD

**Issue by burner1024** [FredrikLindgren/aTweaks#6]
Looks like PnP Undead jacks up XP value for rift guardians (Unseeing Eye bridge, riftcr01-03.cre), which creates a possibility of XP farming by repeatedly choosing wrong answers.
Granted, that has to be done intentionally, but still, in vanilla they are worth 0 XP.

**Comment by FredrikLindgren** [comment]
It was an oversight. A fix has been added.
