### ISSUE TITLE
Stutter zombie fl#lowm.baf

### ISSUE THREAD

**Issue by burner1024** [FredrikLindgren/aTweaks#7]
Getting serious stutter in upper chiontar. Tracked it down to https://github.com/FredrikLindgren/aTweaks/blob/07d7bade42f25bb34aa8a7681fe94671c1076f1b/atweaks/baf/undead/fl%23lowm.baf#L85
NoAction fires rapidly, bringing FPS to single numbers.
```~ATWEAKS/SETUP-ATWEAKS.TP2~ #2 #160 // No-muertos PnP: v4.51 BWP Fix```

**Comment by FredrikLindgren** [comment]
Does it improve if you False() that block? The idea of the block is to improve performance by cutting script evaluation short if there's no one around. I'm not familiar with it degrading performance.

**Comment by burner1024** [comment]
Sorry, looks like I was mistaken. It's not related to the script, but it was the only one popping in dialog window, so I thought it was the cultprit.
